x-common: &common
  logging:
    driver: "json-file"
    options:
      max-size: "500m"
      max-file: "5"
      compress: "true"
  networks:
    - cb-fe-network
    - cb-be-network
  restart:
    unless-stopped

services:
  proxy-service:
    <<: *common
    container_name: proxy-service
    platform: linux/amd64
    build: .
    image: collabberry/proxy-service:latest
    environment:
      SSL_CERT_PATH: /etc/nginx/ssl/star.collabberry.xyz.crt
      SSL_CERT_KEY_PATH: /etc/nginx/ssl/star.collabberry.xyz.key
      FRONTEND_DOMAIN: app.collabberry.xyz
      BACKEND_DOMAIN: api.collabberry.xyz
      FRONTEND_CONTAINER_ADDR: http://frontend-app:4100
      BACKEND_CONTAINER_ADDR: http://backend:3000
    volumes:
      - ./ssl/:/etc/nginx/ssl/
    ports:
      - 443:443
      - 80:80

networks:
  cb-fe-network:
    name: deployment_collabberry-frontend
    external: true
  cb-be-network:
    name: deployment_collabberry-backend
    external: true
